source "https://rubygems.org"

# Specify your gem's dependencies in activerecord_associations_one_to_many.gemspec

gem "rake", "~> 12.0"
gem "rspec", "~> 3.0"
gem "require_all", "~> 3.0"

gem "pry", "~> 0.14.1"

gem "activerecord", "~> 5.2"
gem "sinatra-activerecord", "~> 2.0"

gem "sqlite3", "~> 1.3.6"

group :test do 
  gem "faker", "~> 2.18"
  gem "timecop", "~> 0.9.4"
  gem 'database_cleaner', git: 'https://github.com/bmabey/database_cleaner.git'
end