source "https://rubygems.org"

# Specify your gem's dependencies in intro_to_databases_and_activerecord.gemspec

gem "rake", "~> 12.0"

gem "require_all", "~> 3.0"

gem "pry", "~> 0.14.1"

gem "activerecord", "~> 5.2"
gem "sinatra-activerecord", "~> 2.0"

gem "sqlite3", "~> 1.3.6"

gem "faker", "~> 2.18"

group :test do
  gem "rspec", "~> 3.0"
  gem 'database_cleaner', git: 'https://github.com/bmabey/database_cleaner.git'
end
